name: conferenceapp
description: Flutter Europe conference app

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.3.9'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  camera: ^0.10.0+4
  characters: ^1.2.1
  cloud_firestore: ^4.1.0
  collection: ^1.16.0
  contentful_rich_text: ^2.0.0
  contentful: ^3.0.5
  csv: ^5.0.1
  dotted_border: ^2.0.0+3

#  dynamic_theme: ^1.0.1
  dynamic_themes: ^1.1.0


  equatable: ^2.0.5
  expandable: ^5.0.1
  extended_image: ^6.3.2
  # fast_qr_reader_view: ^0.2.0
  mobile_scanner: ^3.0.0-beta.2
  feature_discovery: ^0.14.1
    #git: https://github.com/ayalma/feature_discovery.git
  file_picker: ^5.2.2
  firebase_analytics: ^10.0.6
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_messaging: ^14.1.2
  # firebase_ml_vision: ^0.12.0+3
  google_ml_kit: ^0.13.0
  firebase_performance: ^0.9.0+6
  firebase_remote_config: ^3.0.6
  firebase_auth_web: ^5.1.3
  flare_flutter: ^3.0.2
  flutter_bloc: ^8.1.1
  flutter_custom_clippers: ^2.0.0
  flutter_local_notifications: ^12.0.4
  fluttertoast: ^8.1.1
  http: ^0.13.5
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  json_serializable: ^6.5.4
  line_icons: ^2.0.1
  package_info: ^2.0.2
  pedantic: ^1.11.1
  provider: ^6.0.4
  qr_flutter:
    git: 
      url: https://github.com/theyakka/qr.flutter.git
      ref: master
  rxdart: ^0.27.7
  share: ^2.0.4
  shared_preferences: ^2.0.15
  smooth_star_rating_nsafe: ^1.0.0+1
  timeago: ^3.3.0
  url_launcher: ^6.1.7
  vibration: ^1.7.6
  #snapfeed: ^0.1.0+1 #capture in-app user feedback, wishes, ratings and much more
  flutter_bugfender: ^2.1.0
  stack_trace: ^1.10.0
  flutter_markdown: ^0.6.13
  # add_2_calendar: ^2.2.2

  cupertino_icons: ^1.0.5
dependency_overrides:
#  flutter_bugfender:
    # path: ../BugfenderSDK-Flutter
#    git:
#      url: https://github.com/orestesgaolin/BugfenderSDK-Flutter
#      ref: d8ed5c7

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.4
  build_runner: ^2.3.0
  mockito:
#  screen: ^0.0.5

flutter:
  uses-material-design: true

  assets:
   - assets/flare/
   - assets/

  fonts:
    - family: PTSans
      fonts:
        - asset: assets/PT_Sans/PTSans-Bold.ttf
          weight: 600
        - asset: assets/PT_Sans/PTSans-Regular.ttf
          weight: 400
        - asset: assets/PT_Sans/PTSans-Italic.ttf
          # weight: 500
        - asset: assets/PT_Sans/PTSans-BoldItalic.ttf
          # weight: 600