name: conferenceapp
description: konferencje snyiwizje.pl
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.3.10'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.0
  camera: ^0.10.1
  characters: ^1.2.1
  cloud_firestore: ^4.3.1
  cloud_firestore_web: ^3.2.1
  collection: ^1.16.0
  contentful_rich_text: ^2.0.0
  contentful: ^3.0.5
  csv: ^5.0.1
  dotted_border: ^2.0.0+3

  # device_preview: ^1.1.0
  # preview: ^0.0.8
  #  dynamic_theme: ^1.0.1
  dynamic_themes: ^1.1.0

  js: ^0.6.5
  equatable: ^2.0.5
  expandable: ^5.0.1
  extended_image: ^6.3.4
  # fast_qr_reader_view: ^0.2.0
  # mobile_scanner: ^3.0.0-beta.4
  feature_discovery: ^0.14.1
  #git: https://github.com/ayalma/feature_discovery.git
  file_picker: ^5.2.5
  firebase_analytics: ^10.1.0
  firebase_analytics_web: ^0.5.1+8
  firebase_auth: ^4.2.5
  firebase_auth_web: ^5.2.4
  firebase_core: ^2.4.1
  firebase_core_web: ^2.1.0
  #  firebase_crashlytics: ^3.0.6
  firebase_messaging: ^14.2.1
  firebase_messaging_web: ^3.2.11
  # firebase_ml_vision: ^0.12.0+3
  google_ml_kit: ^0.13.0
  firebase_performance: ^0.9.0+9
  firebase_remote_config: ^3.0.9
  flare_flutter: ^3.0.2
  flutter_bloc: ^8.1.1
  flutter_custom_clippers: ^2.1.0
  flutter_local_notifications: ^13.0.0
  fluttertoast: ^8.1.2
  http: ^0.13.5
  hydrated_bloc: ^9.0.0
  intl: ^0.18.0
  line_icons: ^2.0.1
  package_info_plus: ^3.0.2
  provider: ^6.0.5
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
      ref: master
  rxdart: ^0.27.7
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  smooth_star_rating_nsafe: ^1.0.0+1
  timeago: ^3.3.0
  url_launcher: ^6.1.7
  vibration: ^1.7.6
  #snapfeed: ^0.1.0+1 #capture in-app user feedback, wishes, ratings and much more
  # flutter_bugfender: ^2.1.0
  stack_trace: ^1.11.0
  flutter_markdown: ^0.6.13
  add_2_calendar: ^2.2.3
  change_app_package_name: ^1.1.0
  json_annotation: ^4.7.0

  cupertino_icons: ^1.0.5
  cloud_firestore_odm: ^1.0.0-dev.45
  date_time_picker: ^2.1.0
  uuid: ^3.0.7
  google_mlkit_barcode_scanning: ^0.5.0
  meta: ^1.8.0
  args: ^2.3.1
  path: ^1.8.2
  logging: ^1.1.0

dependency_overrides:
  test_api: 0.4.17
  stack_trace: 1.10.0
  intl: ^0.17.0
  #  flutter_bugfender:
  # path: ../BugfenderSDK-Flutter
#    git:
#      url: https://github.com/orestesgaolin/BugfenderSDK-Flutter
#      ref: d8ed5c7
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.22.1
  build_runner: ^2.3.3
  mockito: null
  cloud_firestore_odm_generator: ^1.0.0-dev.45
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.1
#  screen: ^0.0.5
flutter:
  uses-material-design: true

  assets:
    - assets/flare/
    - assets/

  fonts:
    - family: PTSans
      fonts:
        - asset: assets/PT_Sans/PTSans-Bold.ttf
          weight: 600
        - asset: assets/PT_Sans/PTSans-Regular.ttf
          weight: 400
        - asset: assets/PT_Sans/PTSans-Italic.ttf
          # weight: 500
        - asset: assets/PT_Sans/PTSans-BoldItalic.ttf
          # weight: 600
flutter_intl:
  enabled: true
